name: CI

on:
    push:
        branches:
            - '2.x'
            - '2.next'
    pull_request:
        branches:
            - '*'
    workflow_dispatch:

permissions:
    contents: read # to fetch code (actions/checkout)

jobs:
    testsuite-linux:
        runs-on: ubuntu-24.04
        strategy:
            fail-fast: false
            matrix:
                php-version: [ '8.1', '8.2', '8.3', '8.4', '8.5' ]
                db-type: [ sqlite, mysql, mariadb, pgsql ]

        services:
            mariadb:
                image: mariadb:11
                env:
                    MARIADB_ROOT_PASSWORD: root
                    MARIADB_DATABASE: cakephp
                ports:
                    - 3307:3306
                options: >-
                    --health-cmd "mariadb-admin ping -h localhost -proot"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
            postgres:
                image: postgres:14
                env:
                    POSTGRES_PASSWORD: postgres
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            -   uses: actions/checkout@v7

            -   name: Setup MySQL
                if: matrix.db-type == 'mysql'
                run: |
                    sudo service mysql start
                    mysql -h 127.0.0.1 -u root -proot -e 'CREATE DATABASE cakephp;'

            -   name: Install MariaDB dump tools
                if: matrix.db-type == 'mariadb'
                run: sudo apt-get install mariadb-client

            -   name: Setup Postgres
                if: matrix.db-type == 'pgsql'
                run: |
                    PGPASSWORD=postgres psql -h 127.0.0.1 -U postgres -c 'GRANT ALL ON SCHEMA public to postgres;'

            -   name: Install pg_dump
                if: matrix.db-type == 'pgsql'
                run: sudo apt-get install postgresql-client

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    extensions: mbstring, intl, ${{ matrix.db-type == 'sqlite' && 'pdo_sqlite' || matrix.db-type == 'pgsql' && 'pdo_pgsql' || 'pdo_mysql' }}
                    ini-values: zend.assertions=1
                    coverage: pcov

            -   name: Composer install
                uses: ramsey/composer-install@v4
                with:
                    dependency-versions: ${{ matrix.dependencies }}
                    composer-options: ${{ matrix.composer-options }}

            -   name: Run PHPUnit
                run: |
                    if [[ ${{ matrix.db-type }} == 'sqlite' ]]; then
                        export DB_URL=sqlite:///testdb.sqlite3
                    fi
                    if [[ ${{ matrix.db-type }} == 'mysql' ]]; then
                        export DB_URL=mysql://root:root@127.0.0.1/cakephp
                    fi
                    if [[ ${{ matrix.db-type }} == 'mariadb' ]]; then
                        export DB_URL=mysql://root:root@127.0.0.1:3307/cakephp
                    fi
                    if [[ ${{ matrix.db-type }} == 'pgsql' ]]; then
                        export DB_URL=postgres://postgres:postgres@127.0.0.1/postgres
                    fi
                    if [[ ${{ matrix.php-version }} == '8.2' ]]; then
                        vendor/bin/phpunit --coverage-clover=coverage.xml
                    else
                        vendor/bin/phpunit
                    fi

            -   name: Code Coverage Report
                if: success() && matrix.php-version == '8.2'
                uses: codecov/codecov-action@v6
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    slug: LordSimal/cakephp-dump-sql

    cs-stan:
        name: Coding Standard & Static Analysis
        runs-on: ubuntu-22.04

        steps:
            -   uses: actions/checkout@v7

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.3'
                    extensions: mbstring, intl
                    coverage: none
                    tools: cs2pr

            -   name: Composer install
                uses: ramsey/composer-install@v4

            -   name: Run phpcs
                if: always()
                run: vendor/bin/phpcs --report=checkstyle src/ tests/ | cs2pr

            -   name: Run phpstan
                if: always()
                uses: docker://ghcr.io/phpstan/phpstan:2-php8.4
                with:
                    args: analyse --error-format=github

            -   name: Run psalm
                if: always()
                uses: docker://ghcr.io/danog/psalm:7.0.0-beta19
                with:
                    args: /composer/vendor/bin/psalm --no-cache --output-format=github
